### ISSUE TITLE
Missing LICENSE File

### ISSUE THREAD

**Issue by kurtseifried** [kimtaeyoon83/mcp-server-youtube-transcript#5]
This repository does not have a LICENSE file (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). If you have already picked a license and specified it somewhere (e.g. in package.json) please simply create a copy of the license in a LICENSE file to make it easier to see which license is in use. If you have nbot picked a license please consider using the MIT, Apache 2.0, GPL or BSD license, The website https://choosealicense.com/ can be of assistance if you are unsure which one to pick.

**Comment by kimtaeyoon83** [comment]
Thank you for bringing this to our attention. I have added a LICENSE file to the repository using the MIT license.

You can now find the complete license terms in the LICENSE file. Closing this issue as resolved.
